var config ={
    callback:{
        onClick:function (id) {
            console.info("contextmenu onclick : " + id);
        }
    }
}

var items = [
    {
        id:"01",
        name:"01都是负担0000我们的长长长长长长",
        img:"assets/image/nav-folder.png",
        shortcutKey:"01",
        type:'group',
        children:[
            {
                id:"011",
                name:"011",
                img:"",
                shortcutKey:"011",
                type:'item',
            },{
                id:"012",
                name:"012",
                img:"",
                shortcutKey:"",
                type:'group',
                children:[{
                    id:"0121",
                    name:"0121",
                    img:"",
                    shortcutKey:"",
                    type:'item'
                }]
            }
        ]
    },{
    id:"02",
    name:"02",
    img:"",
    shortcutKey:"ctrl+r",
    type:'item',
    disable:true
},{
    type:"separator"
},{
    id:"03",
    name:"03",
    img:"",
    shortcutKey:"ctrl+l",
    type:'item',
},
    {
        id:"03",
        name:"01都是负担0000我们的长长长长长长",
        img:"assets/image/nav-folder.png",
        shortcutKey:"01",
        type:'group',
        children:[
            {
                id:"031",
                name:"011",
                img:"",
                shortcutKey:"011",
                type:'item',
            },{
                id:"032",
                name:"032",
                img:"",
                shortcutKey:"",
                type:'group',
                children:[{
                    id:"0321",
                    name:"0321",
                    img:"",
                    shortcutKey:"",
                    type:'item'
                }]
            }
        ]
    },{
    id:"04",
    name:"04",
    img:"",
    shortcutKey:"ctrl+l",
    type:'item',
},{
    id:"05",
    name:"05",
    img:"",
    shortcutKey:"ctrl+l",
    type:'item',
},{
    id:"06",
    name:"06",
    img:"",
    shortcutKey:"ctrl+l",
    type:'item',
},
]